import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="es">
      <body>
				<Navbar/>
				<main>
					{children}
				</main>
			</body>
    </html>
  );
}

export default RootLayout;